### ISSUE TITLE
SpatialPooler - SDR integration

### ISSUE THREAD

**Issue by ctrl-z-9000-times** [htm-community/nupic.cpp#121]
The Spatial Pooler should use the new SDR class.

Why: The SDR class should make the code shorter and easier to follow.  Also these changes will make issue #86 easier to implement.  

API Compatibility: I will maintain the current public API alongside the new SDR API.  The current API will be rewritten to copy its data into & out of the SDR structure.  Once these changes are accepted then we can start rewriting all of the surrounding code to use SDRs as well, and eventually perhaps we can remove the current API.

SDR API: How should users interact with the SP after this change?  I think that the following method should work very similar to what's there now:
    `void compute(SDR *input, bool learn, SDR *activeColumns)`

**Comment by breznak** [comment]
> API Compatibility: I will maintain the current public API alongside the new SDR API. The current API will be rewritten to copy its data into & out of the SDR structure 

Yes, that sounds good. 
- Maybe? wrap the old API in #ifdef API_COMPATIBILITY_v1 but I don't know if it's worth 

> SDR API: How should users interact with the SP after this change? I think that the following method should work very similar to what's there now:
void compute(SDR *input, bool learn, SDR *activeColumns)

- Just use references instead of pointers, saves troubles.

**Comment by dkeeney** [comment]
> void compute(SDR *input, bool learn, SDR *activeColumns)
This would break the Network framework and not be compatible with the API spec.

**Comment by breznak** [comment]
> This would break the Network framework and not be compatible with the API spec. 

Should not: 

> will maintain the current public API alongside the new SDR API. The current API will be rewritten to copy its data into & out of the SDR structure.

**Comment by dkeeney** [comment]
Do we really want to add the overhead of two copies?  Isn't there a way to initialize the SDR class with a pointer to an already populated array without a copy?

Of course, we would have to change the plugin's Input and Output types to be Byte rather than Real32 in the Spec class.   But you still break existing python code.

**Comment by ctrl-z-9000-times** [comment]
> isn't there a way to initialize the SDR class with a pointer to an already populated array without a copy?

There is a way to expose the SDRs data pointer, and to write to it directly.  I hope in the future (after much refactoring) to pass SDRs around directly, and possibly via the Network framework.

**Comment by breznak** [comment]
On Tue, 27 Nov 2018 at 18:29, David Keeney <notifications@github.com> wrote:

> Do we really want to add the overhead of two copies? Isn't there a way to
> initialize the SDR class with a pointer to an already populated array
> without a copy?
>
the set methods can assign memory to sdr (I think?)
Even though, I except gains from faster internal loops with sparse, let’s
see if that justifies in/out conversion

Of course, we would have to change the plugin's Input and Output types to
> be Byte rather than Real32 in the Spec class. But you still break existing
> python code.
>
We can keep it real, 😉 I think more gain would come from sparse than data
type

-- 
Marek Otahal :o)

**Comment by ctrl-z-9000-times** [comment]
Also, Sdr.set will assign memory from a vector only.  It calls std::vector.swap()

**Comment by dkeeney** [comment]
You are talking about a LOT of refactoring, not just in the C++ code but in Python.

Remember that the objective of the nupic.cpp community project is to retain the nupic API so that existing Python code could be used with it (using Python3).   [http://nupic.docs.numenta.org/stable/guides/network.html](http://nupic.docs.numenta.org/stable/guides/network.html)
More specific to Spatial Pooling [http://nupic.docs.numenta.org/stable/api/algorithms/spatial-pooling.html](http://nupic.docs.numenta.org/stable/api/algorithms/spatial-pooling.html)

**Comment by dkeeney** [comment]
Maybe we can do something with the PyBind11 bindings to make the translation but hiding a lot of stuff might not be a good thing. 

Given a numpy array, (we can get a pointer to its buffer), is there a way to use that pointer in your SDR class like a wrapper without copying the buffer?  This is for both input and output.  If we can do that we are golden.

**Comment by ctrl-z-9000-times** [comment]
> the objective of the nupic.cpp community project is to retain the nupic API

Thats not one of my goals, especially not in the long term.  I was hoping at some point to have versioned releases so that we can break backwards compatiblity.

**Comment by dkeeney** [comment]
Then who will use it?

**Comment by ctrl-z-9000-times** [comment]
Who uses it now?

When I first came upon nupic i made a snide remark about biologists and computers, and left to write my own htm.  I recently came back to this repository to find that it compiled more easily (i suspect that you had a hand in that dkeeney). The first thing i did was replace the insertion sort with std::sort.  There is a lot of good work in this repo, but IMHO it is still a work in progress, not an established standard.

**Comment by dkeeney** [comment]
Sorry, I did not mean for the remark to be negative.  We need to think about who the users are.

This library is intended to be a Python extension for those parts of code that are not very fast.  I personally would like to make it more than that such that someone could build an HTM app using just C++ or CSharp....but we are not there yet.

In the mean time the primary users would be people that have written Python apps against the C++ extension or are using any of the large body of existing Python apps in the numenta repository that leverage against the C++ extension all based on this API.

Nobody is using our community version right now because it is work-in-progress but I would hope that we can get this to a point where the Python users can point their Python apps to our C++ extension rather than the numenta repository version hopefully because it will be faster and easier to use (and supports Python 3.x).    Python 2.7 becomes end-of-life next year so they will be looking for a C++ extension that can use Python 3.x.

If we change the API, even a little bit, that would probably not happen. So that is why I am so insistent that we keep to that interface.

Now, I think your SDR class has a place.  We just need to figure out how to work it in so that the API still works. The Network framework uses the Array class as a wrapper on the SDR buffers.  I would like to see the SDR class replace the Array class.  But somehow we need to figure out how to incorporate buffer pointers from numpy or CSharp managed space where we don't control the allocation.

**Comment by ctrl-z-9000-times** [comment]
> the objective of the nupic.cpp community project is to retain the nupic API

Does this extend to public methods ending in '\_' ?  The SP is full of these, such as 'inhibitColumnsGlobal_'.  Some of these methods have python bindings too.

**Comment by dkeeney** [comment]
> Does this extend to public methods ending in '_'

That is a good question.  Any method or variable with a name ending in '_' is by convention a local method or intended for local use.  I expect that the authors intention is that it not be part of the API and that any Python code that references it could probably break.

Although we don't want to break any code if we can help it, I think our guide should be the written API documentation.  That does give us a lot of latitude because there are a lot of things not documented or are not very clear.  It is my hope that this definition would limit the damage to small amounts of code that perhaps took some liberties.  We do not have a lot of resources and some Python code may be someone's personal code that we would not have access to. The API documentation is not entirely up-to-date or perhaps even wrong in places.  We should follow the Python implementation in the numenta repository in those cases; again to avoid breaking code.

For example, the Collection class is a container of objects indexed by name.  So obviously it should be implemented as a map. (However it was implemented as a vector with a serial lookup; probably because SWIG did not handle maps).  This is used to hold pointers to the official list of regions added to a Network object and the Collection is returned by the regions() function.  I want to change this to be a map that holds a shared_ptr.  The API shows the regions() function but does not say what it returns. I will need to check the Python code to see what Python code it might break and if I can hide the change in the PyBind11 bindings.

I expect that there will be some things that we cannot avoid breaking no matter how hard we try. We will have to document them carefully and hope that the required changes in the Python code is not very extensive or difficult to fix.
