### ISSUE TITLE
NuPIC.cpp boost linking error 

### ISSUE THREAD

**Issue by marty1885** [htm-community/nupic.cpp#162]
Hi
I’m trying out NuPIC.cpp. I have successfully compile NuPIC.cpp. But I can’t link NuPIC.cpp to my previous projects. For some reason the linker can’t find boost function despite I’m linking to boost.

```
> c++ xor.cpp -O3 -o xor -lnupic_core -lboost_system -I /usr/include/eigen3
/usr/bin/ld: /tmp/ccG84dWP.o: in function `_GLOBAL__sub_I__Z5noisev':
xor.cpp:(.text.startup+0x2b): undefined reference to `boost::system::generic_category()'
/usr/bin/ld: xor.cpp:(.text.startup+0x30): undefined reference to `boost::system::generic_category()'
/usr/bin/ld: xor.cpp:(.text.startup+0x35): undefined reference to `boost::system::system_category()'
collect2: error: ld returned 1 exit status
```

What’s happening?
OS: Arch Linux
Compiler: GCC 8.2.1
Boost: 1.68.0

**Comment by dkeeney** [comment]
This package is in major flux at the moment.
I am in the process of getting the Python interface to run again using PyBind11 rather than SWIG so some of the .py programs may not work.  So you kind of caught us in the middle of a major change.

If you just want to work with C++ then you can get the repository and checkout branch "pybind11-part3".  We don't have the documentation updated but here is the procedure.
- cd to <Repo>
- mkdir build
- mkdir build/scripts
- cd build/scripts
- cmake ../..
- make install

That should build everything including the statuc C++ library.
If you want to work with Python code....well, some of it might work but we are still trying to get all of the bugs out of the Python-to-C++ interface.  But you can try this:

- cd <Repro>
- python setup.py --user --prefix=

This should build everything and install the extension library in Python 2.7.  (Python 3.x is coming).

Hope that helps.

**Comment by dkeeney** [comment]
Oh, I forgot to mention. You need the following prerequisites:  (get the latest of each)
- CMake
- Python 2.7   (Python 3.x will be supported but it will be a little while)
- recent C++ compiler (your GCC 8 compiler is fine)

**Comment by breznak** [comment]
> If you just want to work with C++  

@dkeeney I think the master should be building and passing c++ (with boost installed on system as a prerequisite) just fine (?) 

He is not using python, only cpp (xor.cpp), correct? 

@marty1885 can you try `src/CMakeLists.txt` and find the `benchmark_hotgym` ? This entry serves as an example how to link 3rd party exacutable with this library. Can you modify (just replace with your files) and try that?

**Comment by dkeeney** [comment]
Yes, I guess with C++ only the master would be fine.
But with this branch you don't have to pre-install Boost.  But the branch is in a high state of flux.

**Comment by breznak** [comment]
Or if your project is open-source / have a reproducible demo, you could open a PR with what you are trying to do. That would be easiest for us to debug.

**Comment by breznak** [comment]
Closing as outdated, needsinfo. If the bug still persists, please reopen with additional info. Thanks
