### ISSUE TITLE
error by getting output after region creating

### ISSUE THREAD

**Issue by Thanh-Binh** [htm-community/nupic.cpp#186]
Hi all,
I try to use nupic.cpp for my own application (which runs without any problem with nupic.core). Please notes that I change my codes slightly for adapting to nupic.cpp. 
After regular adding a region into the network, I want to getNodeOutputElementCount of this region.
But by using nupic.cpp I have got the following run-error: 
ERR:  CHECK FAILED: "spec_->outputs.contains(name)" No output named 'feedForwardOutput' in the spec [/home/binh/nupic/nupic.cpp/src/nupic/engine/Region.cpp line 247]
terminate called after throwing an instance of 'nupic::LoggingException'
  what():  CHECK FAILED: "spec_->outputs.contains(name)" No output named 'feedForwardOutput' in the spec
Can any body explain this behavior by nupic.cpp? Thanks

**Comment by breznak** [comment]
Thanks for testing out nupic.cpp! 
@dkeeney will for sure be able to answer that after Christmas.

**Comment by Thanh-Binh** [comment]
@breznak thanks
@dkeeney fine if you fix the bug!

**Comment by dkeeney** [comment]
@Thanh-Binh Sorry for the delay for the Christmas Holiday.  I will address your bug first thing.

What the program is trying to do in getNodeOutputElementCount() is first find the Spec from the Region implementation.  It checks to see if the spec is setting the buffer size.  If not it then asks the region implementation for the buffer size.  If that Region had been one of the C++ built-in regions this would have worked but I think this is a region that was implemented in Python code.  That means that it is trying to fetch the spec info through the C++ to Python interface which we just switched from SWIG to PyBind11.  This was a major change with all new bindings.  I was hoping that this would all just magically work but nothing is that easy...

As I look at this I see that our unit test for this function did indeed fail. There are some other tests that also are still failing in this area and I will work on them one at a time over the next few weeks.  But since you spotted this one I will work on this bug first.

**Comment by Thanh-Binh** [comment]
@dkeeney i work in C++, not Python. Normally, I can get Spec just after creating a region, I.e. after unregisteredRegion()

**Comment by Thanh-Binh** [comment]
@dkeeney my code looks like:
RegionImplFactory::registerRegion("MyOwnRegion", new RegisteredRegionImplCpp<MyOwnRegion>());
Region_Ptr_t testRegion = net->addRegion("testRegion", "MyOwnRegion", "");
RegionImplFactory::unregisterRegion("MyOwnRegion");

auto width = testRegion->getNodeOutputElementCount("feedForwardOutput");

I think, Spec in MyOwnRegion is somehows not fully loaded during creating

**Comment by dkeeney** [comment]
Oh, entirely different problem than I thought.
Two things:
1) RegisteredRegionImplCpp class is a templated class.  Try this.
```
RegionImplFactory::registerRegion("MyOwnRegion", new RegisteredRegionImplCpp<MyOwnRegion>());
```
2) The spec is cached.  
During registration, the RegionImplFactory will add the newly registered RegisteredRegionImplCpp class to a list of registered types.  When addRegion() is called to create an instance of the region, it looks up the region type and obtains a copy of the spec and caches it on the RegisteredRegionImplCpp class which is the container for the region type.  getNodeOutputElementCount() uses the cache to check if the size was specified in the spec.  But if you unregistered the region type already, its not there and thus the exception.

So, if you remove the unregisterRegion() call it should work.

I am thinking that I should fix this so that an instantiated region should have its own cache of the spec such that an unregister will not cause any harm.

**Comment by Thanh-Binh** [comment]
@dkeeney 
To 1.: it is exactly what i did
To 2.: If you do not use unregisterRegion() , then the new concept is different than the original nupic.core, what requires unregisterRegion after addRegion(). 
Why do not we need it?

**Comment by dkeeney** [comment]
unregisterRegion just removes the Region Impl class type from the list in RegionImplFactory.  Once registered a region type can be used as many times as you need to create Region instances of that region type.  You can register as many region types as you need and they all can be active at the same time as long as they have different type names.

When RegionImplFactory is deleted (end of program) it cleans out the list so unregisterRegion() is not really needed.  However it might be useful if you want to register **different** classes with the same Region type name for some reason.  If you need to do that then you will need to unregister the region type before you use that same type name again.  The changes I just made in the getSpec_bug branch will keep the Spec's straight; The original did not. Now a region will retain the Spec and its implementation class that was active at the point when the Region was created.

**Comment by dkeeney** [comment]
If you want to try my fix, it is branch "getSpec_bug" pull request #187 
Or you can wait until it gets reviewed by someone else and pushed to the master.
