### ISSUE TITLE
NTA_ASSERT vs NTA_CHECK

### ISSUE THREAD

**Issue by Thanh-Binh** [htm-community/nupic.cpp#191]
Dear all,
after looking at the current version in the repository, I found that NTA_CHECK is very often used in the codes. It is also recommend to use NTA_ASSERT instead of it, because both do the same thing in the debug mode but in release mode NTA_ASSERT does NOTHING, because release library is compiled WITHOUT using the option NTA_ASSERTIONS_ON.
What do you think?
Thanks, Binh

**Comment by ctrl-z-9000-times** [comment]
Hi @Binh,

Release mode can have bugs too! NTA_CHECK is especially important for user facing API, to protect against common mistakes, fail fast, and give descriptive error messages.

 These checks should not take very long to execute, both because they are typically simple comparisons and because they are run once at the start of library routines.  If there are any specific checks which you think are taking too long, please point them out and maybe we can make them into NTA_ASSERT statements.

Thank you

**Comment by Thanh-Binh** [comment]
Ok. We will keep the check as simple as possible..
