### ISSUE TITLE
Figure removal in types/ , remove Fraction

### ISSUE THREAD

**Issue by breznak** [htm-community/nupic.cpp#229]
- [x] remove types/Fraction
- remove ntypes/Dimensions,
- ntypes/IOBundle
- [x] ntypes/MemoryParser

(I'll have to check these, I can't compile the source code now, just making a note here)

**Comment by dkeeney** [comment]
I need IOBundle for serialization in the NetworkAPI.
Dimensions are used in the Links and some regions.  I would like to get rid of dimensions but it would break the API.

**Comment by ctrl-z-9000-times** [comment]
> ntypes/MemoryParser

I did some research:
```
$ grep -rnl 'MemStream.hpp' src/
src/CMakeLists.txt
src/test/unit/utils/RandomTest.cpp
src/test/unit/ntypes/MemStreamTest.cpp
src/nupic/math/SparseMatrix.hpp
src/nupic/ntypes/MemParser.cpp
src/nupic/engine/YAMLUtils.cpp <- includes does not use MemStream?

$ grep -rnl 'MemParser.hpp' src/
src/CMakeLists.txt
src/test/unit/ntypes/MemParserTest.cpp
src/nupic/math/SparseMatrix.hpp
src/nupic/ntypes/MemParser.cpp
```
`nupic/math/SparseMatrix.hpp` uses both MemStream and MemParser.  No other file appears to use these files, except for some of the test code.

From the docs:
 * Definitions for the MemStream classes
 *
 * These classes implement a stream that uses memory buffer for reading/writing.
 * It is more efficient than using stringstream because it doesn't require
 * making a copy of the data when setting up an input stream for reading or
 * getting the contents of an output stream after it has been written to.
 *
 * These classes operate much like the c++ std deprecated strstream class, and
 * have the same member functions for getting to the buffered data (str(),
 * pcount()) to make them drop-in replacements.

### MemParser class
/// Class for parsing numbers and strings out of a memory buffer.
///
/// This provides a significant performance advantage over using the standard
/// C++ stream input operators operating on a stringstream in memory.
///
/// @b Responsibility
///  - provide high level parsing functions for extracing numbers and strings
///     from a memory buffer
///
/// @b Resources/Ownerships:
///  - Owns a memory buffer that it allocates in it's constructor.
///
/// @b Notes:
///  To use this class, you pass in an input stream and a total # of bytes to
///  the constructor. The constructor will then read that number of bytes from
///  the stream into an internal buffer maintained by the MemParser object.
///  Subsequent calls to MemParser::get() will extract numbers/strings from the
///  internal buffer.

Both of these things seem like premature optimizations.  
* MemStream avoids a copy operation.  On paper, this is a really good thing because copying takes time and not copying takes no time so this is infinitely faster.  In practice copying is fast enough and sharing data buffers is difficult unless everyone uses smart-pointers which std::string & std::stringstream do not use.
* MemParser: isn't standard library fast enough?

**Comment by breznak** [comment]
> Both of these things seem like premature optimizations. 

:+1: agreed, thanks for doing the search and validation!

**Comment by dkeeney** [comment]
Yes, I also breafly looked at Memstream and MemParser as possible code rot. Thanks for doing the full research. 👍

**Comment by ctrl-z-9000-times** [comment]
See also issue #175.

**Comment by ctrl-z-9000-times** [comment]
`type/Fraction` is only used by the UniformLinkPolicy which will hopefull be deleted in PR #271.

```bash
$ grep -rnl 'Fraction.hpp' src/
src/CMakeLists.txt
src/nupic/types/Fraction.cpp
src/test/unit/types/FractionTest.cpp
src/nupic/engine/UniformLinkPolicy.hpp
src/nupic/engine/UniformLinkPolicy.cpp
src/test/unit/engine/UniformLinkPolicyTest.cpp
```

**Comment by dkeeney** [comment]
Yes, I will delete it as part of #271

**Comment by breznak** [comment]
Closing, as MemParser, Fraction have been removed in #277 #271, 
IOBundle, Dimensions are to stay.
