### ISSUE TITLE
Remove old-API methods in SDR-ized classes (TM, SP) 

### ISSUE THREAD

**Issue by breznak** [htm-community/nupic.cpp#337]
Based on our user survey, people care about API-compat in NetworkAPI, otherwise clean,improved code is prefered. 

So, I'm considering removal of the old API compatibility methods (ie `compute(UInt[] data,..)`) in cases where SDR variant exists. 

- this will force us to do the SDR part properly
- will remove confusion
- not hard to convert array[] code/data from SDR use

**Comment by ctrl-z-9000-times** [comment]
I think that the answer to this question is **yes**, the old methods should be replaced with the new & improved API.  I think that this will break a lot of the unit tests which will be a pain in the butt to fix.

You're welcome to start removing the old methods, as long as the new way of using the algorithm is implemented and clearly better than the old way.

**Comment by ctrl-z-9000-times** [comment]
Some thoughts:

We should start with the big user facing methods because it will force the user to convert their code into using SDRs.  Then we can take our time removing the old legacy interfaces, later.
* SpatialPooler::compute
* TemporalMemory::compute & ::activateDendrites
   - The Temporal Memory is not ready for SDRs yet!  See issue #289, the python bindings need work.

**Comment by dkeeney** [comment]
> force the user to convert their code

I don't think you can force anyone to do anything.  Quite likely they will just not use our library if it means having to change a lot of code.

However, changing our .py code (the code we have or will have in our repository) to use the new SDR interface make since.  But if at all possible can you support the old API at the .py bindings by mapping to the new one?

**Comment by breznak** [comment]
>  Quite likely they will just not use our library if it means having to change a lot of code.
> But if at all possible can you support the old API at the .py bindings by mapping to the new one? 

this is not at all about py code, even NetworkAPI will remain unchanged. 
Currently we do support both versions of calling compute(), this proposal is about dropping the compatibility with old API for and exchanging it for better usability and code-cleaness, as we derived from the user survey. 

FYI, the change would be trivial to fix for the end-user 
now 
```
vector in, out; //fill IN with your data
SP.compute(in, out); 
```
changes simply to 
```
SDR in, out; //fill as needed
SP.compute(in, out); 
```

**Comment by dkeeney** [comment]
> Currently we do support both versions of calling compute(),

This is what I was hoping that we would not loose.
But you are correct, the survey did result in saying you can make these kind of changes.
So, I will withdraw my objection.

**Comment by breznak** [comment]
With #348 all public (main) classes now use (only) the SDR interface
