### ISSUE TITLE
Grid Cells Encoder: provide plot()

### ISSUE THREAD

**Issue by breznak** [htm-community/nupic.cpp#399]
to allow to visualize the reciptive field of the encoder at any time. 

- move the `plot` code from `__init__` to encoders method `plot(self, rows, cols)`
  - ofc, the method should fail if matplotlib import fails (we don't want to force mpl) 
- improve the image descriptions
  - describe axis?
  - add titles to sub-plots? 

The encoder is from #353

**Comment by ctrl-z-9000-times** [comment]
>improve the image descriptions
>    describe axis?
>    add titles to sub-plots?

+1

**Comment by ctrl-z-9000-times** [comment]
I was actually hoping to make all of the encoder viewer programs run by their `__init__` method.  I think it's an intuitive way to use them.

For example instead of the current: `py3 -m nupic.examples.rf_view_ScalarEncoder`
The user would use: `py3 -m nupic.encoders.scalar_encoder`

But the  ScalarEncoder is not located there!  It's at `nupic.bindings.encoders`, not `nupic.encoders`.  We should make the file `nupic.encoders.scalar_encoder` and import the real encoder from bindings so that the user does not need to guess where it is, instead they can find all of their encoders in one convenient module.

> encoders method `plot`

Regardless of where it ends up, it needs to be runnable from the command line.

P.S. Thanks for answering Thanh Binh's question.  I couldn't answer it without being snarky so I didn't.

**Comment by breznak** [comment]
> I was actually hoping to make all of the encoder viewer programs run by their __init__ method. I think it's an intuitive way to use them.

I like the runnable files! :+1: Regarding the `plot`, I just think it could be useful even for the user, so suggestinjg move from init, to self.plot()

**Comment by ctrl-z-9000-times** [comment]
Resolved by PR #481
