### ISSUE TITLE
Merge BacktrackingTM from dkeeny

### ISSUE THREAD

**Issue by breznak** [htm-community/nupic.cpp#45]
Hi @dkeeney ! 
I'd like to merge your C++ implementation of Backtracking TM. 
From 
https://github.com/dkeeney/nupic.core/tree/base 
I have cloned the repo and can cherry-pick the commits. Just headsup: is the development finished?Any tests? etc.

**Comment by dkeeney** [comment]
I just now pushed up my latest changes.
It passes the unit tests.

However, the Backtracking TM is not intended to work with the original
nupic release.
It is intended to work with the SPRegion and TMRegion regions so that the
entire package can be used as a C++ only system without any Python.

The Python 3.x and CSharp interfaces are still being worked on.

Dave
========
