### ISSUE TITLE
Removal/rewrite of TP(=Cells4), BacktrackingTM in favor of TM

### ISSUE THREAD

**Issue by breznak** [htm-community/nupic.cpp#95]
- [x] TP/Cells4 & related classes account for a huge number of old/ugly code
- [x] TM is currently being used instead of TP for most(all?) use-cases
- [x] find on forums, etc if TP has still a valid use-case. Where is it better performing than TM? 
 --- https://github.com/htm-community/nupic.cpp/issues/327#issue-420300926 
   - BackTM is slightly better at Anomaly (NAB) 
- [ ] remove TP/Cells4 from our codebase 
  - [ ] remove BacktrackingTM 

EDIT: more discussion on why those should be removed here https://github.com/htm-community/nupic.cpp/issues/327

**Comment by dkeeney** [comment]
BacktrackingTM is based on Cells4.  If you remove Cells4, BacktrackingTM will not run.
The normal TM uses Connections for the same functionality as provided by Cells4 for BacktrackingTM.

**Comment by breznak** [comment]
I see, let's keep it then. Though Cells4 looks quite unmaintained, one day we could replace it with Connections.

**Comment by dkeeney** [comment]
Perhaps the real question is should BacktrackingTM be kept.   I ported this
to C++ but maybe we should delete both python and C++ versions.   But first
lets get python 3 working.

**Comment by breznak** [comment]
@ctrl-z-9000-times @dkeeney can you please ask in the forums (HTM hackers?)/ our thread with poll, if people still use TP(Cells4) or BackTM? 
If noone uses it, I'm for removal of both; 
otherwise, let's put a warning on being untested and obsoleted, and let the code be until it breaks.

**Comment by Thanh-Binh** [comment]
I am still use BackTM due to good anomaly detection, but I do not need BackTMRegion. Thanks

**Comment by ctrl-z-9000-times** [comment]
Thats a great idea breznak.  Earlier i said consensus but i did not ask our users!

**Comment by dkeeney** [comment]
> I am still use BackTM due to good anomaly detection, but I do not need BackTMRegion. Thanks

See...we do still have users.  Lets not be quite so quick to throw this out.  I think it has value for comparison against other techniques that might be developed.

But asking on the forum is also a good idea. @ctrl-z-9000-times you did such a good job last time, can you do this again?

**Comment by breznak** [comment]
> use BackTM due to good anomaly detection 

Thanks for the input! Could you please post a kind of problem where TM (vs BackTM) is falling short? So we can replicate it?

**Comment by ctrl-z-9000-times** [comment]
I'm in the process of writing the forum post.

In this post I will also bring up the issue of decoding & topDownCompute (#297), since they are also not biological and hard to implement.

I will post a draft here when it's written.

**Comment by ctrl-z-9000-times** [comment]
# Biological Constraints

We're considering dropping support for several features which are not biologically plausible, but which may be useful nonetheless.  

## Summary of the features in question:

### BacktrackingTM
This is a variant of the Temporal Memory algorithm.  It is specialized for anomaly detection, and on the Numenta Anomaly Benchmark it scores approximately 5% higher than the regular Temporal Memory. 

* It is not biologically plausible.
* Numenta has stopped working on it in favor of the regular TM.
* It should probably only be used for anomaly detection.
* It is not in the published literature.  Details about how it works are hard to find, and even we the maintainers can not explain what all of the code does.

### TopDownCompute & Decode
The purpose of both of these methods is to do the inverse of the HTM algorithms.  The decode methods reverse the encoding process, taking an encoded SDR and returning which inputs likely created it.  The TopDownCompute methods reverse the HTM algorithms, and find the inputs which likely resulted in the output.

* None of the core algorithms currently support these methods.
* The Spatial Pooler process could in theory be reversed, but this is unimplemented and unproven.
* The Temporal Memory can not be inverted, these methods simply can not be implemented for it.
* There are fundemential limitations on the accuracy of these methods, since the HTM discards a significant amount of information.

## My questions to you all are:
1) Do you use any of these features, currently or maybe in the future?
2) If yes, for what applications do you use these features?  Tell us about your use cases.

We will leave this discussion open until [2 weeks from posting date] before making a decision and acting on it.

**Comment by dkeeney** [comment]
Looks good to me 👍
